/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import MongoCrud.conectaMongo;


/**
 *
 * @author igoor
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro = new javax.swing.JPanel();
        possuoCadastro = new javax.swing.JButton();
        insereNick = new javax.swing.JTextField();
        insereSenha = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        mostrarSenha = new javax.swing.JCheckBox();
        bgCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        painelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        possuoCadastro.setContentAreaFilled(false);
        possuoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        possuoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                possuoCadastroActionPerformed(evt);
            }
        });
        painelCadastro.add(possuoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 220, 20));
        painelCadastro.add(insereNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, -1));
        painelCadastro.add(insereSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 240, -1));

        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        painelCadastro.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 260, 20));

        cadastrar.setContentAreaFilled(false);
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        painelCadastro.add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 320, 50));

        mostrarSenha.setText("Mostrar Senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });
        painelCadastro.add(mostrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 110, 20));

        bgCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cadastro.png"))); // NOI18N
        painelCadastro.add(bgCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void possuoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_possuoCadastroActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_possuoCadastroActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        new telaPrincipal().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String nome = insereNick.getText(); //Lê o Jlalbel
        String senha = insereSenha.getText();

        conectaMongo conn = new conectaMongo(); //Conecta no mongo
        conn.insertValue(nome, senha);
        conn.getValues();

        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        if (mostrarSenha.isSelected()) {
            insereSenha.setEchoChar((char) 0);
        } else {
            insereSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bgCadastro;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField insereNick;
    private javax.swing.JPasswordField insereSenha;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JButton possuoCadastro;
    // End of variables declaration//GEN-END:variables
}
