/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;


import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author igoor
 */
public class casaHogwarts extends javax.swing.JFrame {

    /**
     * Creates new form casaHogwarts
     */
    public casaHogwarts() {
        initComponents();
        this.setResizable(false);
        this.progressBar.setMaximum(100);
        this.progressBar.setValue(0);
        progressBar.setStringPainted(true); // Para exibir o valor percentual
        new Thread() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    progressBar.setValue(i);

                    try {
                        sleep(30);
                    } catch (InterruptedException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
                dispose();
                Random random = new Random();
                int telaAleatoria = random.nextInt(4) + 1;

                switch (telaAleatoria) {
                    case 1:
                        new grifinoria1().setVisible(true);
                        break;
                    case 2:
                        new sonserina1().setVisible(true);
                        break;
                    case 3:
                        new lufalufa1().setVisible(true);
                        break;
                    case 4:
                        new corvinal1().setVisible(true);
                        break;
                }
                System.out.println(telaAleatoria);
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCasaHogwarts = new javax.swing.JPanel();
        casaHogwarts = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa de Hogwarts");

        painelCasaHogwarts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casaHogwarts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/preCasas.gif"))); // NOI18N
        painelCasaHogwarts.add(casaHogwarts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));
        painelCasaHogwarts.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 416, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCasaHogwarts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCasaHogwarts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(casaHogwarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(casaHogwarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(casaHogwarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(casaHogwarts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new casaHogwarts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casaHogwarts;
    private javax.swing.JPanel painelCasaHogwarts;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
