/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import MongoCrud.conectaMongo;
import javax.swing.JOptionPane;

/**
 *
 * @author igoor
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        /*insereNick.setBackground(new java.awt.Color(0,0,0,0));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        insereNick = new javax.swing.JTextField();
        insereSenha = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        logar = new javax.swing.JButton();
        mostrarSenha = new javax.swing.JCheckBox();
        bgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insereNick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        insereNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereNickActionPerformed(evt);
            }
        });
        painelLogin.add(insereNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, -1));

        insereSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        painelLogin.add(insereSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 240, -1));

        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        painelLogin.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 240, 20));

        logar.setContentAreaFilled(false);
        logar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarActionPerformed(evt);
            }
        });
        painelLogin.add(logar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 330, 50));

        mostrarSenha.setText("Mostrar Senha");
        mostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });
        painelLogin.add(mostrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        painelLogin.add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        new Cadastro().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarActionPerformed
        String nome = insereNick.getText(); // Obtém o nome de usuário inserido
        String senha = insereSenha.getText(); // Obtém a senha inserida

        if (verificarCredenciais(nome, senha)) {
            JOptionPane.showMessageDialog(null, "Login bem-sucedido! Bem-vindo " + nome);
            new selecaoPersonagem().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Login falhou. Verifique suas credenciais.");
        }
    }
    
    public boolean verificarCredenciais(String nome, String senha) {
        conectaMongo conn = new conectaMongo(); // Conecta ao MongoDB
        return conn.verificarLogin(nome, senha);
    }//GEN-LAST:event_logarActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        if (mostrarSenha.isSelected()) {
            insereSenha.setEchoChar((char) 0);
        } else {
            insereSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void insereNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insereNickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JTextField insereNick;
    private javax.swing.JPasswordField insereSenha;
    private javax.swing.JButton logar;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JPanel painelLogin;
    // End of variables declaration//GEN-END:variables
}
