/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author igoor
 */
public class quiz1 extends javax.swing.JFrame {

    private boolean respostaSelecionada = false;

    public quiz1() {
        initComponents();
        this.setResizable(false);
        grupoRespostas.add(resp1);
        grupoRespostas.add(resp2);
        grupoRespostas.add(resp3);
        grupoRespostas.add(resp4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRespostas = new javax.swing.ButtonGroup();
        painelQuiz = new javax.swing.JPanel();
        resp1 = new javax.swing.JRadioButton();
        resp2 = new javax.swing.JRadioButton();
        resp3 = new javax.swing.JRadioButton();
        resp4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        bgQuiz1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz - Primeira Pergunta");

        painelQuiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resp1.setBorder(null);
        resp1.setContentAreaFilled(false);
        resp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp1ActionPerformed(evt);
            }
        });
        painelQuiz.add(resp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 430, 40));

        resp2.setBorder(null);
        resp2.setContentAreaFilled(false);
        resp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp2ActionPerformed(evt);
            }
        });
        painelQuiz.add(resp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 430, 50));

        resp3.setBorder(null);
        resp3.setContentAreaFilled(false);
        resp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp3ActionPerformed(evt);
            }
        });
        painelQuiz.add(resp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 430, 50));

        resp4.setBorder(null);
        resp4.setContentAreaFilled(false);
        resp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp4ActionPerformed(evt);
            }
        });
        painelQuiz.add(resp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 430, 50));

        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        painelQuiz.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 80, 20));

        bgQuiz1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Quiz1.png"))); // NOI18N
        painelQuiz.add(bgQuiz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (respostaSelecionada == true) {
            new quiz2().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void resp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp1ActionPerformed
        respostaSelecionada = true; // Marcar que uma resposta foi selecionada
    }//GEN-LAST:event_resp1ActionPerformed

    private void resp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp2ActionPerformed
        respostaSelecionada = true; // Marcar que uma resposta foi selecionada
    }//GEN-LAST:event_resp2ActionPerformed

    private void resp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp3ActionPerformed
        respostaSelecionada = true; // Marcar que uma resposta foi selecionada
    }//GEN-LAST:event_resp3ActionPerformed

    private void resp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp4ActionPerformed
        respostaSelecionada = true; // Marcar que uma resposta foi selecionada
    }//GEN-LAST:event_resp4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgQuiz1;
    private javax.swing.ButtonGroup grupoRespostas;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel painelQuiz;
    private javax.swing.JRadioButton resp1;
    private javax.swing.JRadioButton resp2;
    private javax.swing.JRadioButton resp3;
    private javax.swing.JRadioButton resp4;
    // End of variables declaration//GEN-END:variables
}
