/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author igoor
 */
public class selecaoPersonagem extends javax.swing.JFrame {
 
    private static int selecaoP;

    public static int getSelecaoP() {
        return selecaoP;
    }

    public static void setSelecaoP(int selecaoP) {
        selecaoPersonagem.selecaoP = selecaoP;
    }
    
    public selecaoPersonagem() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSelecao = new javax.swing.JPanel();
        imagemHarry = new javax.swing.JButton();
        imagemRon = new javax.swing.JButton();
        imagemHermione = new javax.swing.JButton();
        imagemSelecaoPersonagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleção de Personagem");

        painelSelecao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagemHarry.setBorderPainted(false);
        imagemHarry.setContentAreaFilled(false);
        imagemHarry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagemHarry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemHarryActionPerformed(evt);
            }
        });
        painelSelecao.add(imagemHarry, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 400));

        imagemRon.setBorderPainted(false);
        imagemRon.setContentAreaFilled(false);
        imagemRon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagemRon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemRonActionPerformed(evt);
            }
        });
        painelSelecao.add(imagemRon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 400));

        imagemHermione.setBorderPainted(false);
        imagemHermione.setContentAreaFilled(false);
        imagemHermione.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagemHermione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemHermioneActionPerformed(evt);
            }
        });
        painelSelecao.add(imagemHermione, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 220, 400));

        imagemSelecaoPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selecaoDePersonagem.png"))); // NOI18N
        painelSelecao.add(imagemSelecaoPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSelecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSelecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imagemRonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemRonActionPerformed
        dispose();
        new cartaRon().setVisible(true);
        selecaoP = 1;
    }//GEN-LAST:event_imagemRonActionPerformed

    private void imagemHarryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemHarryActionPerformed
        dispose();
        new cartaHarry().setVisible(true);
        selecaoP = 2;
    }//GEN-LAST:event_imagemHarryActionPerformed

    private void imagemHermioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemHermioneActionPerformed
        dispose();
        new cartaHermione().setVisible(true);
        selecaoP = 3;
    }//GEN-LAST:event_imagemHermioneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selecaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selecaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selecaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selecaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selecaoPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imagemHarry;
    private javax.swing.JButton imagemHermione;
    private javax.swing.JButton imagemRon;
    private javax.swing.JLabel imagemSelecaoPersonagem;
    private javax.swing.JPanel painelSelecao;
    // End of variables declaration//GEN-END:variables
}
