/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;


/**
 *
 * @author igoor
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        botaoComoJogar = new javax.swing.JButton();
        botaoSaibaMais = new javax.swing.JButton();
        botaoPlay = new javax.swing.JButton();
        botaoQuit = new javax.swing.JButton();
        imagemPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoComoJogar.setBorderPainted(false);
        botaoComoJogar.setContentAreaFilled(false);
        botaoComoJogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComoJogarActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoComoJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 110, 20));

        botaoSaibaMais.setBorderPainted(false);
        botaoSaibaMais.setContentAreaFilled(false);
        botaoSaibaMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSaibaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSaibaMaisActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoSaibaMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 110, 20));

        botaoPlay.setContentAreaFilled(false);
        botaoPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlayActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 210, 60));

        botaoQuit.setContentAreaFilled(false);
        botaoQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQuitActionPerformed(evt);
            }
        });
        painelPrincipal.add(botaoQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 42, 40, 40));

        imagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/telaPrincipal.png"))); // NOI18N
        painelPrincipal.add(imagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComoJogarActionPerformed
        dispose();
        new comoJogar().setVisible(true);
    }//GEN-LAST:event_botaoComoJogarActionPerformed

    private void botaoSaibaMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSaibaMaisActionPerformed
        dispose();
        new saibaMais().setVisible(true);
    }//GEN-LAST:event_botaoSaibaMaisActionPerformed

    private void botaoPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlayActionPerformed
        dispose();
        new Cadastro().setVisible(true);
    }//GEN-LAST:event_botaoPlayActionPerformed

    private void botaoQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComoJogar;
    private javax.swing.JButton botaoPlay;
    private javax.swing.JButton botaoQuit;
    private javax.swing.JButton botaoSaibaMais;
    private javax.swing.JLabel imagemPrincipal;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
